server:
  port: 12001
spring:
  application:
    name: microservice-elasticsearch    # 项目名称尽量用小写
  jpa:
    database: MYSQL
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties: 
      hibernate: 
        dialect : org.hibernate.dialect.MySQL5Dialect
  datasource:                           # 指定数据源
    url: jdbc:mysql://127.0.0.1:3306/spring_cloud_study
    driverClassName: com.mysql.jdbc.Driver
    username: root  
    password: root
  data: 
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9200 
      local: false 
      repositories: 
         enabled: true
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch.youran.persistence: ERROR
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/    # 指定注册中心的地址
  instance:
    preferIpAddress: true