server:
  port: 8040
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vangyong/microservice-segema.git/     # 配置git仓库的地址
          search-paths: config-repo                                     # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: vangyong@126.com                                    # git仓库的账号
          password:  wy513288                                           # git仓库的密码